### ISSUE TITLE
unknown sql type: uuid

### ISSUE THREAD

**Issue by insanebaba** [quek/arysn#2]
Currently not able to generate Structs for tables with uuid primary key

**Comment by quek** [comment]
Thanks for the Issue.
We've released version 0.1.7 with uuid support, please give it a try.

**Comment by insanebaba** [comment]
It works, Thank you so much. Closing the issue

**Comment by insanebaba** [comment]
I faced an issue, that I used **geometric point** without SRID. I'm not able to use it. Is there a way it can be added?
