### ISSUE TITLE
multiple issues with generated entities

### ISSUE THREAD

**Issue by insanebaba** [quek/arysn#6]
1. Options are not handled or connected.

I think some types that are Option types are not connected well.
I get below error after generating entities
```
mismatched types
expected struct `uuid::Uuid`
     found enum `std::option::Option<uuid::Uuid>`
```

2. HasOneConfig foreign key is on self table and not remote.

If **Plant** has a **breed** then the **breed_id** will be on plant table and not the **Breed** table.

3. Weird methods generated

```
    |
443 |                 let children_builder = Dish::select().dishId().r#in(ids);
    |                                                       ^^^^^^ method not found in `backend::database::models::dish_impl::DishBuilder`
    | 
```

**Comment by quek** [comment]
Thank's for your issue.
Please show me your create table statements and define_ar codes.
I need to reproduce that bug.
