### ISSUE TITLE
Raw SQL support

### ISSUE THREAD

**Issue by insanebaba** [quek/arysn#7]
Is there any way I can write raw sql and get result mapped to structs?

**Comment by quek** [comment]
Try something like this.

```rust
let rows = conn.query("SELECT * FROM users WHERE ...", &params[...]).await?;
let mut result: Vec<User> = rows.into_iter().map(|row| User::from(row)).collect();
```

https://docs.rs/tokio-postgres/0.5.5/tokio_postgres/struct.Client.html#method.query
